name: PermOrMoney
main: ru.progrm_jarvis.permormoney.PermOrMoney
version: 1.0.2
author: PROgrm_JARvis (JARvis (Пётр) PROgrammer)
depend: [Vault]
commands:
  permormoney:
    description: 'Give permission or perform command!'
    aliases: [pom, porm, permom, permorm, pomoney, pormoney]
    permission: permormoney.command.permormoney
    usage: /permormoney <player> <permission> <eco> [command]